apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: $KUBE_NAMESPACE-secret-$CI_COMMIT_REF_SLUG
  namespace: $KUBE_NAMESPACE
  labels:
    # Standard labels - follow these patterns, additional labels can be added if needed
    environment: $DOPPLER_ENVIRONMENT                  # This is our standard, do not change (output pulled from doppler will be either dev_,dev,stg,or prd)
    gitlab_project: $CI_PROJECT_NAME                   # This is our standard, do not change
    gitlab_pipeline_id: "$CI_PIPELINE_ID"              # This is our standard, do not change
    project_owner: web                                 # Select only from one of the following (web, api, sre, data, or rock)
# Fetches any SECRET_ prefixed secrets from a dooppler config via the ClusterSecretStore and rewrites them to remove the SECRET_ prefix before deploying to the cluster as a secret object
spec:
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        path: SECRET_
      rewrite:
        - regexp:
            source: SECRET_(.*)
            target: $1
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: $KUBE_NAMESPACE-secret-$CI_COMMIT_REF_SLUG
